# Generated by Django 5.1.5 on 2025-01-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloggy", "0002_post_post_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="uncategorized", max_length=255),
        ),
    ]
