# Generated by Django 5.1.5 on 2025-01-25 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloggy", "0003_category_post_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="post_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
