# Generated by Django 5.1.5 on 2025-02-04 02:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloggy", "0006_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.TextField(
                default="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec tincidunt orci. Morbi auctor orci vel est sodales euismod. Maecenas eros diam, hendrerit sed eros at, interdum aliquam orci Duisv. varius vestibulum vulputate Duis.",
                max_length=230,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
