# Generated by Django 5.1.5 on 2025-02-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloggy", "0007_category_description_post_snippet_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=230),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="snippet",
            field=models.TextField(max_length=230),
        ),
    ]
